name: mazes
channels:
  - defaults
dependencies:
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.9.12
  - setuptools=61.2.0
  - sqlite=3.38.2
  - tzdata=2022a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - pillow==9.1.0
